### ISSUE TITLE
Missing a declaration of MASK_GAIN in stateprediction

### ISSUE THREAD

**Issue by quantrung9** [corey-snyder/STREETS#12]
Hi @corey-snyder,

I noticed that this line https://github.com/corey-snyder/STREETS/blob/master/benchmark/stateprediction/dataloader.py#L35.

```
self.roadmask_dict[view] = (imread(roadmask_path)/MASK_GAIN).astype(np.uint8)
```

causes `NameError: name 'MASK_GAIN' is not defined` when run `python train.py` 

I think it would be great if you could show me what the MASK_GAIN variable is and How I should define it. Thank you so much.

I am looking forward to hearing from you soon.

**Comment by corey-snyder** [comment]
Hello,

Sorry for the slow response. I believe you can simply set MASK_GAIN = 1. I think the normalization has no effect since it appears the road masks are not used in the state prediction codes.

Also, I apologize for the "roadmask_path" being hard-coded to my own file system. I will clean these kinds of issues up in a future update to the repository!

**Comment by quantrung9** [comment]
Thanks for your answer, @corey-snyder.
